services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - shortener
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=shortener
      - DB_USERNAME=shortener_user
      - DB_PASSWORD=shortener_pass

  nginx:
    image: nginx:alpine
    container_name: shortener_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shortener
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: shortener_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shortener
      MYSQL_USER: shortener_user
      MYSQL_PASSWORD: shortener_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shortener

networks:
  shortener:
    driver: bridge

volumes:
  db_data:
    driver: local
